version: '3'
services:
  dev-db:
    image: postgres:12
    volumes:
      - db:/var/lib/mysql-dev
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD : 123
      POSTGRES_DB: carsly

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  carsly-backend:
    build:
      context: ..
      dockerfile: ./packages/backend/Dockerfile
    depends_on:
      - dev-db
    environment:
      NODE_ENV: development
      PORT: 5174
      DATABASE_URL: ${DATABASE_URL}
      __AT_SECRET: ${__AT_SECRET}
      __RT_SECRET: ${__RT_SECRET}
    ports:
      - '5174:5174'
    restart: always

  carsly-frontend:
    build: 
      context: ..
      dockerfile: ./packages/web/Dockerfile
    environment:
      VITE_BACKEND_URL : "http://localhost:5174"
    ports:
      - '5173:5173'

volumes:
  db: 